# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-18 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40, unique=True)),
                ('img', models.FileField(upload_to='photos/')),
                ('descripcion', models.TextField(verbose_name='Descripci\xf3n')),
            ],
        ),
    ]
